#Projects settings
project:
  config:
    SQLDBEnable: true
    SQLDBEntities: com.mokhovav.boardgames.authorization
    baseSequrity: true
    MongoDBEnable: true
    first: true
    second: false


#server:
#  servlet:
#    session:
#      tracking-modes: COOKIE
#      cookie:
#        http-only: true
#        secure: true
#      timeout: 15m


#MongoDB config

#Hibernate config
hibernate:
  sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  driver-class-name: org.postgresql.Driver
  ddl-auto: update
  host: localhost
  port: 5432
  database: projectDB
  username: user
  password: user

#MongoDb config
mongoDB:
  database: projectDB
  host: localhost
  port: 27017
  username: root
  password: toor

#slf4j Logger
logging:
  file:
    name: logs/application-debug.log
    max-size: 1MB
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"
    rolling-file-name: logs/archived/application-debug.%d{yyyy-MM-dd}.%i.log
  level:
    root: info
    com.mokhovav: debug
